---
- name: "install_RedHat | Install the SEP sesam repo"
  yum_repository:
    name: sep-sesam
    description: "SEP sesam repo"
    baseurl: "{{ sep_sesam_repo }}"
    gpgkey: "{{ sep_sesam_gpg_key }}"
    gpgcheck: yes

- name: "install_RedHat | Install the SEP sesam packages"
  yum:
    name: "{{ sep_sesam_pkg[sep_sesam_host_type] }}"
    state: present
...
